# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces\SR_ResDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SR_Results(object):
    def setupUi(self, SR_Results):
        SR_Results.setObjectName("SR_Results")
        SR_Results.resize(947, 633)
        self.gridLayout = QtWidgets.QGridLayout(SR_Results)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.selLRButton = QtWidgets.QPushButton(SR_Results)
        self.selLRButton.setObjectName("selLRButton")
        self.verticalLayout.addWidget(self.selLRButton)
        self.LRViewer = QtWidgets.QLabel(SR_Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LRViewer.sizePolicy().hasHeightForWidth())
        self.LRViewer.setSizePolicy(sizePolicy)
        self.LRViewer.setMinimumSize(QtCore.QSize(256, 256))
        self.LRViewer.setStyleSheet("background-color:white")
        self.LRViewer.setText("")
        self.LRViewer.setObjectName("LRViewer")
        self.verticalLayout.addWidget(self.LRViewer)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selHRButton = QtWidgets.QPushButton(SR_Results)
        self.selHRButton.setObjectName("selHRButton")
        self.verticalLayout_2.addWidget(self.selHRButton)
        self.HRViewer = QtWidgets.QLabel(SR_Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HRViewer.sizePolicy().hasHeightForWidth())
        self.HRViewer.setSizePolicy(sizePolicy)
        self.HRViewer.setMinimumSize(QtCore.QSize(256, 256))
        self.HRViewer.setStyleSheet("background-color:white")
        self.HRViewer.setText("")
        self.HRViewer.setObjectName("HRViewer")
        self.verticalLayout_2.addWidget(self.HRViewer)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bicLabel = QtWidgets.QLabel(SR_Results)
        self.bicLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bicLabel.setObjectName("bicLabel")
        self.verticalLayout_3.addWidget(self.bicLabel)
        self.BicViewer = QtWidgets.QLabel(SR_Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BicViewer.sizePolicy().hasHeightForWidth())
        self.BicViewer.setSizePolicy(sizePolicy)
        self.BicViewer.setMinimumSize(QtCore.QSize(256, 256))
        self.BicViewer.setStyleSheet("background-color:white")
        self.BicViewer.setText("")
        self.BicViewer.setObjectName("BicViewer")
        self.verticalLayout_3.addWidget(self.BicViewer)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SRCNNLabel = QtWidgets.QLabel(SR_Results)
        self.SRCNNLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SRCNNLabel.setObjectName("SRCNNLabel")
        self.verticalLayout_4.addWidget(self.SRCNNLabel)
        self.SRCNNViewer = QtWidgets.QLabel(SR_Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SRCNNViewer.sizePolicy().hasHeightForWidth())
        self.SRCNNViewer.setSizePolicy(sizePolicy)
        self.SRCNNViewer.setMinimumSize(QtCore.QSize(256, 256))
        self.SRCNNViewer.setStyleSheet("background-color:white")
        self.SRCNNViewer.setText("")
        self.SRCNNViewer.setObjectName("SRCNNViewer")
        self.verticalLayout_4.addWidget(self.SRCNNViewer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SRGANLabel = QtWidgets.QLabel(SR_Results)
        self.SRGANLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SRGANLabel.setObjectName("SRGANLabel")
        self.verticalLayout_5.addWidget(self.SRGANLabel)
        self.SRGANViewer = QtWidgets.QLabel(SR_Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SRGANViewer.sizePolicy().hasHeightForWidth())
        self.SRGANViewer.setSizePolicy(sizePolicy)
        self.SRGANViewer.setMinimumSize(QtCore.QSize(256, 256))
        self.SRGANViewer.setStyleSheet("background-color:white")
        self.SRGANViewer.setText("")
        self.SRGANViewer.setObjectName("SRGANViewer")
        self.verticalLayout_5.addWidget(self.SRGANViewer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ESRGANLabel = QtWidgets.QLabel(SR_Results)
        self.ESRGANLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ESRGANLabel.setObjectName("ESRGANLabel")
        self.verticalLayout_6.addWidget(self.ESRGANLabel)
        self.ESRGANViewer = QtWidgets.QLabel(SR_Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ESRGANViewer.sizePolicy().hasHeightForWidth())
        self.ESRGANViewer.setSizePolicy(sizePolicy)
        self.ESRGANViewer.setMinimumSize(QtCore.QSize(256, 256))
        self.ESRGANViewer.setStyleSheet("background-color:white")
        self.ESRGANViewer.setText("")
        self.ESRGANViewer.setObjectName("ESRGANViewer")
        self.verticalLayout_6.addWidget(self.ESRGANViewer)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.startButton = QtWidgets.QPushButton(SR_Results)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_8.addWidget(self.startButton)
        self.saveButton = QtWidgets.QPushButton(SR_Results)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_8.addWidget(self.saveButton)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(SR_Results)
        QtCore.QMetaObject.connectSlotsByName(SR_Results)

    def retranslateUi(self, SR_Results):
        _translate = QtCore.QCoreApplication.translate
        SR_Results.setWindowTitle(_translate("SR_Results", "SR Results"))
        self.selLRButton.setText(_translate("SR_Results", "Select Low Resolution Image"))
        self.selHRButton.setText(_translate("SR_Results", "Select High Resolution Image"))
        self.bicLabel.setText(_translate("SR_Results", "BIC"))
        self.SRCNNLabel.setText(_translate("SR_Results", "SRCNN"))
        self.SRGANLabel.setText(_translate("SR_Results", "SRGAN"))
        self.ESRGANLabel.setText(_translate("SR_Results", "ESRGAN"))
        self.startButton.setText(_translate("SR_Results", "Start"))
        self.saveButton.setText(_translate("SR_Results", "Save"))

